config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :slides
  end
  resources :slides
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/slide.rb
class Slide < ApplicationRecord

validates :name, presence: true
has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

scope :publication, -> { where(published: true) }
scope :min_publication, -> { where('DateTime(published_from) < ? ', DateTime.now ) }
scope :max_publication, -> { where('DateTime(published_to) > ?', DateTime.now ) }

end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /admin/slides
  # GET /admin/slides.json
  def index
    @slides = Slide.all
  end

  # GET /admin/slides/1
  # GET /admin/slides/1.json
  def show
  end

  # GET /admin/slides/new
  def new
    @slide = Slide.new
  end

  # GET /admin/slides/1/edit
  def edit
  end

  # POST /admin/slides
  # POST /admin/slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to [:admin, @slide], notice: 'Slide was successfully created.' }
        format.json { render action: 'show', status: :created, location: @slide }
      else
        format.html { render action: 'new' }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/slides/1
  # PATCH/PUT /admin/slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to [:admin, @slide], notice: 'Slide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/slides/1
  # DELETE /admin/slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to admin_slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:name, :desc_left, :desc_right, :picture, :published, :published_from,
      :published_to)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  # GET /slides.json
  def index
    # requete de base que l'on va passer au model
    # @slides = Slide.where("DateTime(published_from) < ? AND DateTime(published_to) > ? AND published == ?", DateTime.now, DateTime.now, true)

    # Grace au scope créé dans le model on simplifie la lecture du code
    @slides = Slide.publication.min_publication.max_publication
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to @slide, notice: 'Slide was successfully created.' }
        format.json { render :show, status: :created, location: @slide }
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to @slide, notice: 'Slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:name, :desc_left, :desc_right, :picture, :published, :published_from, :published_to)
    end
end

app/helpers/admin/slides_helper.rb
module Admin::SlidesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/admin/slides/_form.html.erb
<%= form_for([:admin, @slide], html: { multipart: true }) do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc_left %><br>
    <%= f.text_area :desc_left %>
  </div>
  <div class="field">
    <%= f.label :desc_right %><br>
    <%= f.text_area :desc_right %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
   <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label :published_from %><br>
    <%= f.date_field :published_from %>
  </div>
  <div class="field">
    <%= f.label :published_to %><br>
    <%= f.date_field :published_to %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/slides/edit.html.erb
<h1>Editing slide</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @slide] %> |
<%= link_to 'Back', admin_slides_path %>

app/views/admin/slides/index.html.erb
<h1>Listing slides</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc left</th>
      <th>Desc right</th>
      <th>Picture</th>
      <th>Published</th>
      <th>Published_from</th>
      <th>Published_to</th>
    </tr>
  </thead>

  <tbody>
    <% @slides.each do |slide| %>
      <tr>
        <td><%= slide.name %></td>
        <td><%= slide.desc_left %></td>
        <td><%= slide.desc_right %></td>
        <td><%= image_tag slide.picture.url(:thumb) %></td>
        <td><%= slide.published %></td>
        <td><%= slide.published_from %></td>
        <td><%= slide.published_to %></td>
        <td><%= link_to 'Show', [:admin, slide] %></td>
        <td><%= link_to 'Edit', edit_admin_slide_path(slide) %></td>
        <td><%= link_to 'Destroy', [:admin, slide], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slide', new_admin_slide_path %>

app/views/admin/slides/new.html.erb
<h1>New slide</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_slides_path %>

app/views/admin/slides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slide.name %>
</p>

<p>
  <strong>Desc left:</strong>
  <%= @slide.desc_left %>
</p>

<p>
  <strong>Desc right:</strong>
  <%= @slide.desc_right %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @slide.picture.url %>
</p>

<%= link_to 'Edit', edit_admin_slide_path(@slide) %> |
<%= link_to 'Back', admin_slides_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sliders</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/slides/_form.html.erb
<%= form_for(slide) do |f| %>
  <% if slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :desc_left %>
    <%= f.text_area :desc_left %>
  </div>

  <div class="field">
    <%= f.label :desc_right %>
    <%= f.text_area :desc_right %>
  </div>
  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field  :picture %>
  </div>
  <div class="field">
    <%= f.label :published_from %><br>
    <%= f.date_field :published_from %>
  </div>
  <div class="field">
    <%= f.label :published_to %><br>
    <%= f.date_field :published_to %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slides/edit.html.erb
<h1>Editing Slide</h1>

<%= render 'form', slide: @slide %>

<%= link_to 'Show', @slide %> |
<%= link_to 'Back', slides_path %>

app/views/slides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slides</h1>

<table>

  <tbody>
    <% @slides.each do |slide| %>
      <tr>
        <td><%= slide.name %></td>
        <td><%= slide.desc_left %></td>
        <td><%= image_tag slide.picture.url(:medium) %></td>
        <td><%= slide.desc_right %></td>
        <td><%= link_to 'Show', slide %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slide', new_slide_path %>

app/views/slides/new.html.erb
<h1>New Slide</h1>

<%= render 'form', slide: @slide %>

<%= link_to 'Back', slides_path %>

app/views/slides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slide.name %>
</p>

<p>
  <strong>Desc Left</strong>
  <%= @slide.desc_left %>
</p>

<p>
  <strong>Desc Right</strong>
  <%= @slide.desc_right %>
</p>

<p>
  <strong>Picture</strong>
  <%= image_tag @slide.picture.url %>
</p>

<%= link_to 'Edit', edit_slide_path(@slide) %> |
<%= link_to 'Back', slides_path %>